### PR TITLE
segger: system-view: include path fix (+ some minor improvements) - regression

### LINKED ISSUE #61133: segger: system-view: include path priority issue (regression)
**Describe the bug**

The Zephyr-specific Segger SystemView configuration is no longer used as an empty file with the same name was inadvertently added to the external segger module with higher import priority during the last Segger module upgrade a few months ago.

**To Reproduce**

1. Build any application with the following configuration:
CONFIG_TRACING=y
CONFIG_THREAD_NAME=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_SYSTEMVIEW=y
2. Start the program
3. An immediate fault caused by infinite recursion will result

**Expected behavior**

The application should start normally and tracing with Segger SystemView should work.

**Impact**

The Segger SystemView tracing integration became unusable (regression).

**Logs and console output**

n/a

**Environment (please complete the following information):**

any - reproduced on Linux

**Additional context**

Fix exists already - PR will be linked.

### PR DESCRIPTION
**Pull request by ghost**
This fixes a regression in the the Segger SystemView integration: The Zephyr-specific Segger SystemView configuration was not used as the same file was added inside this segger module with higher import priority since the last Segger module upgrade a few months ago. This made Segger SystemView unusable (regression).

~~It is proposed to change the custom RTT locking strategy from mutexes to spinlocks:~~
~~* Mutexes caused infinite loops when tracing with Segger SystemView.~~
~~* Spinlocks are more lightweight than mutexes.~~
~~* The prior implementation did not support RTT logging and tracing from ISR context.~~

UPDATE: Spinlock solution withdrawn - see discussion below.

This change is preliminary to https://github.com/zephyrproject-rtos/zephyr/pull/61090, see further details there.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/61133

### CODE REVIEW

**Comment by ghost** [comment]
@nashif Guess you want to have a look as this enables [a PR](https://github.com/zephyrproject-rtos/zephyr/pull/61090) that has been automatically assigned to you.

**Comment by carlescufi** [comment]
But won't this then introduce significant additional latency to ISRs in general? You are gonna be disabling interrupts every time RTT is used.

File: Config/SEGGER_RTT_Conf.h [hunk 1]
```diff
@@ -152,10 +152,10 @@ Revision: $Rev: 24316 $
 #if ((defined(__SES_ARM) || defined(__SES_RISCV) || defined(__CROSSWORKS_ARM) || defined(__GNUC__) || defined(__clang__)) && !defined (__CC_ARM) && !defined(WIN32))
   #if defined(__ZEPHYR__) && defined (CONFIG_SEGGER_RTT_CUSTOM_LOCKING)
     #ifdef CONFIG_MULTITHREADING
```
Comment (carlescufi) [inline Config/SEGGER_RTT_Conf.h]: If you make this change you don't need this `#ifdef` anymore. You can just use `k_spin_(un)lock()` regardless of multithreading or not.

**Review by carlescufi — CHANGES_REQUESTED** [review]

File: Config/SEGGER_RTT_Conf.h (hunk 1 above)
Comment (carlescufi) [reply Config/SEGGER_RTT_Conf.h]: Note: `k_spin_(un)lock` maps directly to `irq_(un)lock` in uniprocessor systems.

File: Config/SEGGER_RTT_Conf.h [hunk 2]
```diff
@@ -152,10 +152,10 @@ Revision: $Rev: 24316 $
...
-      extern void zephyr_rtt_mutex_lock(void);
-      extern void zephyr_rtt_mutex_unlock(void);
-      #define SEGGER_RTT_LOCK() zephyr_rtt_mutex_lock()
-      #define SEGGER_RTT_UNLOCK() zephyr_rtt_mutex_unlock()
+      extern void zephyr_rtt_spin_lock(void);
```
Comment (nordic-krch) [inline Config/SEGGER_RTT_Conf.h]: I'm afraid that this can result in long periods when interrupts are locked since it blocks for RTT API where you write data to it and one can write 10 bytes to RTT is single call but you can also write 1k of data in a single call. In case of logging RTT backend, it writes from lowest priority thread and amount of data depends on internal buffer size which is configurable. By default it's 16 bytes (which result in 4,5us lock time @64MHz). When I increase this buffer to 64 bytes (which is reasonable value) lock time increased to 10us.

**Review by nordic-krch — CHANGES_REQUESTED** [review]

**Comment by nordic-krch** [comment]
> Mutexes caused infinite loops when tracing with Segger SystemView.

Was it cause by attempting to take mutex in the interrupt context when mutex was already taken?

**Comment by ghost** [comment]
UPDATE: Obsolete - see next comment.

>But won't this then introduce significant additional latency to ISRs in general? 
> ...
> I'm afraid that this can result in long periods when interrupts are locked 

@carlescufi @nordic-krch You're right - the RTT API call must not be done with interrupts disabled. Doh!

Being able to trace from ISR context still looks like a must-have requirement: Locking/unlocking, posting to queues, semaphores, etc... An asynchronous tracing approach burns too many cycles overall and is too complex IMO.

The only other ISR-safe locking mechanism, I'm aware of, are "abused" semaphores. But as they must be "no wait" in ISRs that pattern isn't very helpful either unless we spin around them which feels really hacky.

The next best solution, that comes to my mind, is spinning around an atomic variable without locking interrupts:

```
	while (!atomic_cas(&rtt_lock, 0, 1)) {
		arch_nop();
	}
       ...calls to RTT/tracing...
       atomic_clear(&rtt_lock);
```

(Shamelessly copied from the spinlock code.)

Does this still produce unwanted side-effects in practice?

Some random thoughts (maybe wrong/incomplete):
* This blocks the caller context (including any calling ISR) but - as the mutex solution - will be preemted by higher-priority ISRs.
* Other than the mutex solution a blocked thread will not automatically yield. But is that a problem in practice?
  * For tracing its not a bug but a feature.
  * The asynchronous logging thread serializes access, lock contention will not occur at all, right? We just burn a few cycles less for locking which is at worst irrelevant.
  * Synchronous logging will be the same on a single CPU, on multiple CPUs the calling thread will no longer yield. But is that worse in practice? In how many cases do we yield now where spinning would have been more efficient? Does synchronous logging matter at all? Applications that care about latency will not do it.
* In existing applications the RTT lock will only be requested from ISRs for tracing and never for logging - so no potential for regression in that case. In the worst case we gain an additional option (sync RTT logging from ISR) which didn't exist before.

> Mutexes caused infinite loops when tracing with Segger SystemView.
>> Was it cause by attempting to take mutex in the interrupt context when mutex was already taken?

No, that's not the problem. The problem is that locking/unlocking mutexes is a tracing event itself. If tracing events get traced then we have an infinite recursion unless we design some tracing-specific circuit breaker. The solution with atomic_cas() wouldn't require any special treatment of tracing.

File: Config/SEGGER_RTT_Conf.h (hunk 2 above)
Comment (ghost) [reply Config/SEGGER_RTT_Conf.h]: Does copying a single byte require 18 cycles on our target? Wow. I wouldn't have expected that but I also never measured it. In any case your argument is 100% valid independently of the numbers. It's simply inacceptable to delay unrelated ISRs.

**Comment by ghost** [comment]
@carlescufi @nordic-krch While implementing the alternative spinlock solution I realized for the first time that until 7 months ago we already had separate locking solutions for tracing (IRQ lock) and logging (mutex). The root cause for the regression in tracing is an innocent upgrade of the Segger library which introduced an additional SEGGER_SYSVIEW_Conf.h which took precedence over the existing SEGGER_SYSVIEW_Conf.h (which is one of the bugs I fixed w/o fully understanding its impact).

This means that we have no hard reason to change the locking mechanism at all. Just fixing the include priority fixes the regression. Does it still make sense to try out the somewhat leaner "self-made spinlock" solution? In my opinion it smells premature optimization under these conditions (therefore withdrawn). What do you think?

**Review by carlescufi — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
